#!/usr/bin/python

import sys
import os
import re
import urllib
import subprocess


def getlocation(ip):
    result = urllib.urlopen(
        "http://www.ip138.com/ips138.asp?ip=%s&action=2" % ip)
    res = result.readlines()
    result.close()
    for i in res:
        if re.search(".*ul class=\"ul1\".*", i):
            ipblock = i
    if 'ipblock' in dir():
        add1 = ipblock.split("<")[3].split(">")[
            1].decode('gb2312')[6:].encode('utf8')
        add2 = ipblock.split("<")[5].split(">")[
            1].decode('gb2312')[6:].encode('utf8')
        if add1 == add2:
            add = add1
        else:
            add = add1 + " OR " + add2

        return_add = "%s[%s]" % (ip, add)
        # print return_add
        return return_add

    return ip


if __name__ == '__main__':
    #p = re.compile(r"(\d+.\d+.\d+.\d+)")
    # for i,line in enumerate(sys.stdin):
    #    l = p.findall(line)
    #    l = list(set(l))
    # print l
    #
    #    if len(l) == 0:
    #        print line,
    #        continue
    #    else:
    #        for j in l:
    #            line = line.replace(j,getlocation(j))
    #        print line,

    p = re.compile(r"(\d+.\d+.\d+.\d+)")

    while 1:
        line = sys.stdin.readline()
        if not line.strip():
                break

        l = p.findall(line)
        l = list(set(l))
        # print l

        if len(l) == 0:
            print line,
        else:
            for j in l:
                line = line.replace(j, getlocation(j))
            print line,
